# This is an implementation of a model using a random mathematical formula.

In [412]:
import numpy as np
import math
from sklearn.utils import shuffle

In [413]:
data = np.arange(0,1000)
z = np.zeros(1000)

In [414]:
training_data = data[:700]

In [415]:
training_data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [416]:
max1 = training_data.max()
min1 = training_data.min()
max1, min1

(699, 0)

In [417]:
training_data = shuffle(training_data, random_state=0)

In [418]:
training_data

array([306, 604,  40, 493,  14, 548, 267,  31, 252, 103, 675, 278, 536,
       313,  85, 352, 667, 427, 529, 502, 545, 344, 624, 621, 582, 538,
       520, 533, 619,   1, 546, 235, 172,  75, 532, 242, 407, 468, 231,
       229, 181,  27, 210, 401, 364, 465, 471, 569, 463, 592, 356, 646,
       366, 637, 406, 312, 360, 142,   8,  79, 365, 175, 193, 354,  50,
       656, 491, 607, 455, 605, 330,  10,  68, 467, 694, 239, 473, 524,
       230, 575, 650, 358, 318, 268, 635, 457, 122, 302, 251, 626, 157,
       693, 389, 346,  37, 243,  48, 481, 454, 240, 162, 508,  76,  64,
        52, 557, 334, 236, 674, 563, 428, 187, 331, 156, 363, 325, 222,
       435, 456, 470, 113, 697,  97,  18, 506, 301,  55,  49, 380, 466,
       211,  17, 503, 202, 580, 337, 266, 645, 504, 417,  45, 285,  62,
       386, 668, 299, 140, 584, 490, 127, 665, 144,  21, 480, 511,  35,
       412, 272,  77, 249, 333, 374, 263, 101, 279, 196, 294, 170, 460,
       542, 409, 477, 691, 696, 214, 165, 553,  34, 685, 200, 59

In [419]:
v = np.zeros(700)
for i in range(0,700) :
    y = (math.sqrt(max1 - training_data[i]) / 2)
    v[i] = y

In [420]:
v

array([ 9.9121138 ,  4.87339717, 12.83549765,  7.17635005, 13.08625233,
        6.14410286, 10.39230485, 12.92284798, 10.57118726, 12.20655562,
        2.44948974, 10.25914226,  6.38357267,  9.82344135, 12.38951169,
        9.31396801,  2.82842712,  8.24621125,  6.51920241,  7.01783442,
        6.20483682,  9.42072184,  4.33012702,  4.41588043,  5.40832691,
        6.34428877,  6.68954408,  6.44204936,  4.47213595, 13.20984481,
        6.18465844, 10.77032961, 11.47824028, 12.489996  ,  6.46142399,
       10.68877916,  8.54400375,  7.59934208, 10.81665383, 10.83974169,
       11.37980668, 12.9614814 , 11.05667219,  8.63133825,  9.15150261,
        7.64852927,  7.54983444,  5.70087713,  7.68114575,  5.17204022,
        9.26012959,  3.64005494,  9.1241438 ,  3.93700394,  8.55862138,
        9.83615779,  9.20597632, 11.80042372, 13.14343943, 12.4498996 ,
        9.13783344, 11.44552314, 11.24722188,  9.28708781, 12.7377392 ,
        3.27871926,  7.21110255,  4.79583152,  7.81024968,  4.84

In [421]:
model = [training_data, v]

In [422]:
model

[array([306, 604,  40, 493,  14, 548, 267,  31, 252, 103, 675, 278, 536,
        313,  85, 352, 667, 427, 529, 502, 545, 344, 624, 621, 582, 538,
        520, 533, 619,   1, 546, 235, 172,  75, 532, 242, 407, 468, 231,
        229, 181,  27, 210, 401, 364, 465, 471, 569, 463, 592, 356, 646,
        366, 637, 406, 312, 360, 142,   8,  79, 365, 175, 193, 354,  50,
        656, 491, 607, 455, 605, 330,  10,  68, 467, 694, 239, 473, 524,
        230, 575, 650, 358, 318, 268, 635, 457, 122, 302, 251, 626, 157,
        693, 389, 346,  37, 243,  48, 481, 454, 240, 162, 508,  76,  64,
         52, 557, 334, 236, 674, 563, 428, 187, 331, 156, 363, 325, 222,
        435, 456, 470, 113, 697,  97,  18, 506, 301,  55,  49, 380, 466,
        211,  17, 503, 202, 580, 337, 266, 645, 504, 417,  45, 285,  62,
        386, 668, 299, 140, 584, 490, 127, 665, 144,  21, 480, 511,  35,
        412, 272,  77, 249, 333, 374, 263, 101, 279, 196, 294, 170, 460,
        542, 409, 477, 691, 696, 214, 165, 553,  34

In [423]:
testing_data = data[701:]

In [424]:
testing_data

array([701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713,
       714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726,
       727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739,
       740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752,
       753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765,
       766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778,
       779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791,
       792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804,
       805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817,
       818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830,
       831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843,
       844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856,
       857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869,
       870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 88

In [425]:
testing_data = shuffle(testing_data, random_state=0)

In [426]:
testing_data

array([907, 889, 713, 920, 938, 837, 929, 906, 753, 809, 941, 716, 885,
       947, 723, 775, 970, 791, 928, 956, 891, 804, 825, 830, 921, 817,
       895, 986, 995, 950, 793, 767, 709, 823, 918, 851, 877, 883, 999,
       706, 964, 790, 782, 735, 756, 840, 935, 765, 708, 746, 774, 992,
       874, 807, 760, 931, 869, 727, 984, 854, 835, 846, 764, 993, 985,
       923, 990, 812, 721, 747, 857, 927, 973, 728, 845, 959, 738, 798,
       892, 836, 819, 861, 902, 913, 937, 777, 911, 924, 954, 936, 982,
       745, 942, 890, 853, 859, 802, 755, 882, 719, 981, 949, 827, 872,
       772, 926, 972, 915, 988, 914, 855, 860, 734, 784, 948, 761, 868,
       980, 811, 722, 730, 847, 717, 757, 776, 810, 876, 901, 862, 705,
       797, 867, 762, 768, 838, 975, 962, 979, 741, 968, 714, 808, 919,
       704, 858, 826, 725, 731, 778, 977, 909, 720, 953, 930, 969, 781,
       752, 703, 934, 805, 880, 787, 711, 899, 759, 742, 715, 856, 751,
       910, 940, 824, 900, 763, 888, 925, 831, 908, 960, 744, 81

In [427]:
c= [np.zeros(700), np.zeros(700)]
rt = np.zeros(300)
z = np.zeros(300)

In [428]:
for i in testing_data:
    index = 0
    sum = 0
    for j in training_data:
        c[0][index] = math.sqrt((i**2) - (j**2))
        c[1][index] = v[index]
        index += 1
    z = sorted(c[0])
    for t in z[-6:-1]:
        loc = np.where(c[0] == t)
        sum += c[1][loc]
    rt[list(testing_data).index(i)] = sum/5

In [429]:
result = [testing_data, rt]

In [430]:
result

[array([907, 889, 713, 920, 938, 837, 929, 906, 753, 809, 941, 716, 885,
        947, 723, 775, 970, 791, 928, 956, 891, 804, 825, 830, 921, 817,
        895, 986, 995, 950, 793, 767, 709, 823, 918, 851, 877, 883, 999,
        706, 964, 790, 782, 735, 756, 840, 935, 765, 708, 746, 774, 992,
        874, 807, 760, 931, 869, 727, 984, 854, 835, 846, 764, 993, 985,
        923, 990, 812, 721, 747, 857, 927, 973, 728, 845, 959, 738, 798,
        892, 836, 819, 861, 902, 913, 937, 777, 911, 924, 954, 936, 982,
        745, 942, 890, 853, 859, 802, 755, 882, 719, 981, 949, 827, 872,
        772, 926, 972, 915, 988, 914, 855, 860, 734, 784, 948, 761, 868,
        980, 811, 722, 730, 847, 717, 757, 776, 810, 876, 901, 862, 705,
        797, 867, 762, 768, 838, 975, 962, 979, 741, 968, 714, 808, 919,
        704, 858, 826, 725, 731, 778, 977, 909, 720, 953, 930, 969, 781,
        752, 703, 934, 805, 880, 787, 711, 899, 759, 742, 715, 856, 751,
        910, 940, 824, 900, 763, 888, 925, 831, 908