In [1]:
list = [1, 2, 3, 4, 5, 6]

In [15]:
list

[1, 2, 3, 4, 5, 6]

Importin NumPy as np

In [16]:
import numpy as np

Creating a np array (vector type) from a list

In [4]:
arr = np.array(list)

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [25]:
mat = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]


Creating a np array (matrices type) from a list of lists

In [7]:
mat_arr = np.array(mat)

In [19]:
mat_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


'arange' method works similar to Python range method

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

'zeros()' method returns a matrices of 0s. We can choose the dimension by passing a tuple in the argument.

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

'ones' method returns a matrices of 1s. We can choose the dimension by passing a tuple in the argument.

In [27]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

'linspace' method returns evenly spaced numbers over a specified interval.

In [29]:
np.linspace(0, 5, 50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

We can use 'eye' method to create an identity matrix.

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random
Numpy also has lots of ways to create random number arrays:

rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [31]:
np.random.rand(2)

array([0.22320336, 0.84561657])

In [32]:
np.random.rand(7,8)

array([[0.41620621, 0.34237069, 0.81374831, 0.6006453 , 0.23856567,
        0.98240252, 0.77346019, 0.22572627],
       [0.39473783, 0.6849063 , 0.15284642, 0.31948267, 0.67576684,
        0.50322366, 0.81204793, 0.19248861],
       [0.03195648, 0.8223728 , 0.67709336, 0.04939923, 0.58271012,
        0.62209839, 0.16615047, 0.89869167],
       [0.99762065, 0.13946556, 0.89851242, 0.87722412, 0.39836388,
        0.56410471, 0.36695752, 0.64638982],
       [0.65020069, 0.57108392, 0.90612086, 0.86936196, 0.09302454,
        0.71951544, 0.69810265, 0.58826137],
       [0.66312835, 0.58435154, 0.02309568, 0.01013616, 0.41421168,
        0.46589871, 0.07849439, 0.66121855],
       [0.39441145, 0.1799747 , 0.50346096, 0.11513795, 0.01588356,
        0.39178611, 0.69452625, 0.9935616 ]])

randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [39]:
np.random.randn(4,5)

array([[-0.15187606, -0.10169168, -1.08554417,  1.03424539, -0.23268247],
       [ 0.0611221 ,  0.05731588,  1.12693253,  0.03735345,  0.24136859],
       [-0.16675034,  1.21460566, -0.2274767 , -0.97338792,  2.44681126],
       [-0.82005036, -1.09259021,  1.19374501, -0.08421367,  1.22551683]])

randint
Return random integers from low (inclusive) to high (exclusive).

In [37]:
np.random.randint(0, 1000, (5, 5))

array([[222, 188, 216, 414, 761],
       [442, 498, 102, 905, 355],
       [491,  12, 545, 773, 181],
       [613, 567, 510, 144, 690],
       [852, 242, 209,  20,  48]])

# Array attributes

reshape : Returns an array containing the same data with a new shape.

In [50]:
n_arr = np.random.randint(0, 1000, 25)

In [51]:
n_arr

array([354,  20, 861, 796, 998, 709, 783, 315, 198, 464, 781, 927, 582,
       475, 783, 925, 128, 104, 138, 755, 708, 984, 129, 477, 179])

In [53]:
n_arr.reshape(5, 5)

array([[354,  20, 861, 796, 998],
       [709, 783, 315, 198, 464],
       [781, 927, 582, 475, 783],
       [925, 128, 104, 138, 755],
       [708, 984, 129, 477, 179]])

In [54]:
n_arr.reshape(25)

array([354,  20, 861, 796, 998, 709, 783, 315, 198, 464, 781, 927, 582,
       475, 783, 925, 128, 104, 138, 755, 708, 984, 129, 477, 179])


max,min,argmax,argmin : These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax


In [55]:
n_arr.min()

20

In [56]:
n_arr.max()

998

In [57]:
n_arr.argmin()

1

In [58]:
n_arr.argmax()

4

Shape is an attribute that arrays have (not a method)

In [59]:
n_arr.shape

(25,)

In [60]:
n_arr.reshape(5, 5).shape

(5, 5)

dtype : This returns the data type of the object in the array.

In [62]:
n_arr.dtype

dtype('int32')

# NumPy Indexing and Selection

In [63]:
ar = np.arange(70).reshape(7, 10)

In [64]:
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [66]:
ar[3:5, 4:6]

array([[34, 35],
       [44, 45]])

In [69]:
ar[5:, :6]

array([[50, 51, 52, 53, 54, 55],
       [60, 61, 62, 63, 64, 65]])

# NumPy Operations

In [77]:
arr

array([1, 2, 3, 4, 5, 6])

In [78]:
arr + arr

array([ 2,  4,  6,  8, 10, 12])

In [79]:
arr - arr

array([0, 0, 0, 0, 0, 0])

In [80]:
arr * arr

array([ 1,  4,  9, 16, 25, 36])

In [81]:
arr ** arr

array([    1,     4,    27,   256,  3125, 46656], dtype=int32)

In [82]:
arr + 100

array([101, 102, 103, 104, 105, 106])

In [83]:
arr - 100

array([-99, -98, -97, -96, -95, -94])

In [84]:
np.sqrt(arr ** arr)

array([  1.        ,   2.        ,   5.19615242,  16.        ,
        55.90169944, 216.        ])

In [85]:
np.max(arr)

6

In [86]:
arr.max()

6

In [88]:
np.sin(arr / (arr ** arr))

array([8.41470985e-01, 4.79425539e-01, 1.10882629e-01, 1.56243642e-02,
       1.59999932e-03, 1.28600823e-04])

In [91]:
np.log(np.sin(arr / (arr ** arr)))

array([-0.17260375, -0.73516669, -2.19928304, -4.15892377, -6.43775208,
       -8.95879735])

In [92]:
np.exp(np.log(np.sin(arr / (arr ** arr))))

array([8.41470985e-01, 4.79425539e-01, 1.10882629e-01, 1.56243642e-02,
       1.59999932e-03, 1.28600823e-04])